### ISSUE TITLE
DevOps issue in LLVM Bugs notifier

### ISSUE THREAD

**Issue by NickLewisL3H** [CTSRD-CHERI/llvm-project#686]
When submitting a previous issue I received an error:
```
Run actions/github-script@v5
Error: Parameter "key" is required
    at new _ (/home/runner/work/llvm-project/llvm-project/node_modules/mailgun.js/mailgun.node.js:2:8309)
    at e.client (/home/runner/work/llvm-project/llvm-project/node_modules/mailgun.js/mailgun.node.js:2:33909)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4888:56), <anonymous>:7:20)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4889:12)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4927:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
Error: Unhandled error: Error: Parameter "key" is required
```
during https://github.com/CTSRD-CHERI/llvm-project/actions/runs/4435712551/

**Comment by NickLewisL3H** [comment]
And sure enough this issue submission has itself errored:

https://github.com/CTSRD-CHERI/llvm-project/actions/runs/4435992544
